CREATE TABLE public.user_tweets (
     id bigint NOT NULL PRIMARY KEY,
     conversation_id bigint NOT NULL,
     created_at timestamp with time zone NOT NULL,
     tweet text NOT NULL,
     hashtags text[],
     urls text[],
     source text,
     language text,
     retweet_count integer,
     reply_count integer,
     like_count integer,
     quote_count integer,
     in_reply_to_user_id bigint,
     user_id bigint,
     user_screen_name text,
     user_name text,
     user_description text,
     user_location text,
     user_created_at timestamp with time zone,
     user_followers_count integer,
     user_friends_count integer,
     user_statuses_count integer,
     user_verified boolean,
     linked jsonb,
     source_files text[]
 );
